jobs:
  - job: WindowsBuild

    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core sdk 3.0.100-preview6-012264'
      inputs:
        version: '3.0.100-preview6-012264'

    - script: '.\WindowsBuild.ps1'
      displayName: 'Build CoreEngine'

    - script: '.\WindowsBuildTest.cmd EcsTest'
      displayName: 'Build Tests'

  - job: MacOSBuild

    pool:
      name: Hosted macOS
    steps:
    - task: DotNetCoreInstaller@0
      displayName: 'Use .NET Core sdk 3.0.100-preview6-012264'
      inputs:
        version: '3.0.100-preview6-012264'

    - script: ./MacOSBuild.sh
      displayName: 'Build CoreEngine'

    - script: './MacOSBuildTest.sh EcsTest'
      displayName: 'Build Tests'
